services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/var/www/html:cached
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: academia
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  composer:
    image: composer:latest
    container_name: composer
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html

volumes:
  db_data:
